version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  logic-service:
    build: ./logic-service
    depends_on:
      - redis
    deploy:
      replicas: 3

  handler-service:
    build: ./
    ports:
      - "4000-4005:8080"
    deploy:
      replicas: 3
    depends_on:
      - redis
      - logic-service
