version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  logic-service:
    build: ./logic-service
    depends_on:
      - redis

  handler-service:
    build: ./
    ports:
      - "8080-8085:8080"
    depends_on:
      - redis
      - logic-service

#  nginx:
#    image: nginx:latest
#    ports:
#      - "8080:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - handler-service